# Generated by Django 3.0.8 on 2020-08-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pic/<django.db.models.query_utils.DeferredAttribute object at 0x7f7da71af910>'),
        ),
    ]
