# Generated by Django 3.0.8 on 2020-08-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200828_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pic/<built-in function id>'),
        ),
    ]
