# Generated by Django 3.0.8 on 2020-08-29 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200829_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostSubmission',
        ),
    ]
