# Generated by Django 3.0.8 on 2020-08-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('img_url', models.CharField(default='static/default.jpg', max_length=30)),
            ],
        ),
    ]
