# Generated by Django 3.0.8 on 2020-08-29 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_delete_postsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('img_url', models.CharField(default='static/default.jpg', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Bloguser')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bucketlist.Continent')),
            ],
        ),
    ]
